services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/root
    tty: true
    command: "yarn dev"
    working_dir: /root/next_app/nextjs-dashboard/
    # Typescriptでホットリロードを有効化する
    environment:
      - WATCHPACK_POLLING=true
